In [2]:
import numpy as np

In [3]:
# 02- NUMPY INDEXING
arr = np.arange(0,11)

In [4]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_arr = arr[0:6]

In [13]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_arr[:]

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_arr [:] = 99

In [16]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy[:] = 100

In [21]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
# 2d array

In [24]:
arr_2d = np.array([[5,10,25], [20,25,30], [35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 25],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[:2,1:]

array([[10, 25],
       [25, 30]])

In [27]:
arr_2d[:2]

array([[ 5, 10, 25],
       [20, 25, 30]])

In [28]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [29]:
arr = np.arange(1,11)

In [30]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
bool_arr = arr > 5

In [32]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[arr>5] # conditional sleection

array([ 6,  7,  8,  9, 10])

In [35]:
arr[arr<3]

array([1, 2])

In [39]:
arr_2d = np.arange(50).reshape(5,10)

In [40]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [43]:
# NUMPY OPERATIONS
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr - arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [46]:
arr / arr

/var/folders/qt/yzylxnkd2jd79xsznsqtct9c0000gn/T/ipykernel_34044/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [47]:
1 / arr

/var/folders/qt/yzylxnkd2jd79xsznsqtct9c0000gn/T/ipykernel_34044/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [48]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [49]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [50]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [51]:
np.max(arr)

10

In [52]:
arr.max()

10

In [53]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [54]:
np.log(arr)

/var/folders/qt/yzylxnkd2jd79xsznsqtct9c0000gn/T/ipykernel_34044/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [55]:
# 01 - NumPy Arrays
my_list = [1,2,3]

In [58]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [59]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [60]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [62]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.ones(4)

array([1., 1., 1., 1.])

In [64]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [67]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
np.random.rand(5,5)

array([[0.97845197, 0.23422408, 0.55431221, 0.92840768, 0.55025524],
       [0.2960866 , 0.48190503, 0.84108029, 0.53918181, 0.96779385],
       [0.66175257, 0.43967368, 0.85346555, 0.04450348, 0.93567485],
       [0.92727069, 0.87015157, 0.58114016, 0.95505739, 0.04039881],
       [0.15438141, 0.7125497 , 0.61927929, 0.07560779, 0.59409945]])

In [69]:
np.random.randn(2) # random distrubtuions

array([ 0.25182035, -0.58281809])

In [70]:
np.random.randint(1, 100, 10)

array([97, 39, 92, 56, 12,  1, 78,  9, 67, 72])

In [71]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
ranarr = np.random.randint(0,50,10)

In [73]:
ranarr

array([15, 26,  3, 28, 48, 22,  0, 36,  5, 39])

In [74]:
arr.reshape(5,5) # limit using only digits you have in arr, 25 el

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
ranarr.max()

48

In [76]:
ranarr.min()

0

In [77]:
ranarr.argmax()

4

In [78]:
ranarr.argmin()

6

In [80]:
arr.shape

(25,)

In [82]:
arr.dtype

dtype('int64')